use heck::{ToPascalCase, ToSnakeCase};
use indexmap::IndexMap;
use serde_json::Value;

use crate::openrpc::{Info, Method, OpenRpcDoc};

/// Top-level entry: generate a single Rust source file from an OpenRPC document.
pub fn generate(doc: &OpenRpcDoc) -> String {
    let mut ctx = Codegen::default();
    for method in &doc.methods {
        ctx.process_method(method);
    }
    ctx.render(&doc.info)
}

// ─────────────────────────────────────────────────────────────────────────────

#[derive(Default)]
struct Codegen {
    /// Named type definitions, kept in insertion order so dependencies appear
    /// before the types that reference them.
    types: IndexMap<String, String>,
    /// Generated method bodies for the `impl BitcoinRpcClient` block.
    methods: Vec<String>,
}

impl Codegen {
    fn process_method(&mut self, method: &Method) {
        let result_hint = format!("{}Result", method.name.to_pascal_case());
        let result_type = self.schema_to_type(&method.result.schema, &result_hint);

        // "&self" is always first.
        let mut sig_params: Vec<String> = vec!["&self".to_string()];
        // Runtime values passed to the JSON-RPC `params` array.
        let mut call_args: Vec<String> = Vec::new();

        for param in &method.params {
            if param.placeholder {
                // Placeholder: send null on the wire but expose nothing to the caller.
                call_args.push("Value::Null".to_string());
                continue;
            }

            let hint = format!(
                "{}{}",
                method.name.to_pascal_case(),
                param.name.to_pascal_case()
            );
            let base_type = self.schema_to_type(&param.schema, &hint);
            let param_name = safe_ident(&param.name.to_snake_case());

            if param.required {
                sig_params.push(format!("{param_name}: {base_type}"));
                call_args.push(format!("serde_json::to_value({param_name}).unwrap()"));
            } else {
                sig_params.push(format!("{param_name}: Option<{base_type}>"));
                // serde_json serialises None → Value::Null automatically.
                call_args.push(format!("serde_json::to_value({param_name}).unwrap()"));
            }
        }

        let args_expr = if call_args.is_empty() {
            "vec![]".to_string()
        } else {
            format!("trim_trailing_nulls(vec![{}])", call_args.join(", "))
        };

        let doc_comment = format_doc(&method.description, 4);
        let fn_name = method.name.replace('-', "_");

        let body = format!(
            "{doc_comment}    pub fn {fn_name}({sig}) -> Result<{result_type}, Error> {{\n        self.call(\"{rpc}\", {args})\n    }}",
            sig = sig_params.join(", "),
            rpc = method.name,
            args = args_expr,
        );
        self.methods.push(body);
    }

    fn render(&self, info: &Info) -> String {
        let types_block = self.types.values().cloned().collect::<Vec<_>>().join("\n");
        let methods_block = self.methods.join("\n\n");

        // The braces inside the format string that belong to Rust code (not
        // format placeholders) are doubled.
        format!(
r#"// Generated by openrpc-demo from Bitcoin Core's `getopenrpcinfo` RPC.
// {title} {version}
//
// Required Cargo.toml entries for the generated file:
//   [dependencies]
//   base64     = "0.22"
//   serde      = {{ version = "1", features = ["derive"] }}
//   serde_json = "1"
//   ureq       = {{ version = "2", features = ["json"] }}
//
// DO NOT EDIT — regenerate by running openrpc-demo.

#![allow(dead_code, clippy::all)]

use std::collections::HashMap;
use serde::{{Deserialize, Serialize}};
use serde_json::Value;

// ── Error ─────────────────────────────────────────────────────────────────────

#[derive(Debug)]
pub enum Error {{
    Http(Box<ureq::Error>),
    Io(std::io::Error),
    Json(serde_json::Error),
    Rpc {{ code: i64, message: String }},
}}

impl From<ureq::Error> for Error {{
    fn from(e: ureq::Error) -> Self {{ Self::Http(Box::new(e)) }}
}}
impl From<std::io::Error> for Error {{
    fn from(e: std::io::Error) -> Self {{ Self::Io(e) }}
}}
impl From<serde_json::Error> for Error {{
    fn from(e: serde_json::Error) -> Self {{ Self::Json(e) }}
}}
impl std::fmt::Display for Error {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        match self {{
            Self::Http(e) => write!(f, "HTTP: {{e}}"),
            Self::Io(e)   => write!(f, "IO: {{e}}"),
            Self::Json(e) => write!(f, "JSON: {{e}}"),
            Self::Rpc {{ code, message }} => write!(f, "RPC {{}}: {{}}", code, message),
        }}
    }}
}}
impl std::error::Error for Error {{}}

// ── Types ─────────────────────────────────────────────────────────────────────

{types_block}

// ── Client ────────────────────────────────────────────────────────────────────

/// Remove trailing `Value::Null` entries so the server uses its defaults.
fn trim_trailing_nulls(mut args: Vec<Value>) -> Vec<Value> {{
    while args.last() == Some(&Value::Null) {{
        args.pop();
    }}
    args
}}

pub struct BitcoinRpcClient {{
    url:  String,
    auth: String,
}}

impl BitcoinRpcClient {{
    pub fn new(host: &str, port: u16, user: impl AsRef<str>, pass: impl AsRef<str>) -> Self {{
        use base64::Engine as _;
        let encoded = base64::engine::general_purpose::STANDARD
            .encode(format!("{{}}:{{}}", user.as_ref(), pass.as_ref()));
        Self {{
            url:  format!("http://{{host}}:{{port}}/"),
            auth: format!("Basic {{encoded}}"),
        }}
    }}

    fn call<T: for<'de> serde::Deserialize<'de>>(
        &self,
        method: &str,
        params: Vec<Value>,
    ) -> Result<T, Error> {{
        let body = serde_json::json!({{
            "jsonrpc": "2.0",
            "id":      "openrpc-demo",
            "method":  method,
            "params":  params,
        }});

        // Bitcoin Core returns HTTP 500 for RPC-level errors but still sends a
        // valid JSON body, so we extract it from both the Ok and Status arms.
        let response: Value = match ureq::post(&self.url)
            .set("Authorization", &self.auth)
            .send_json(body)
        {{
            Ok(resp)                      => resp.into_json()?,
            Err(ureq::Error::Status(_, resp)) => resp.into_json()?,
            Err(e)                        => return Err(Error::Http(Box::new(e))),
        }};

        if let Some(err) = response.get("error").filter(|e| !e.is_null()) {{
            return Err(Error::Rpc {{
                code:    err["code"].as_i64().unwrap_or(-1),
                message: err["message"].as_str().unwrap_or("unknown").to_owned(),
            }});
        }}

        Ok(serde_json::from_value(response["result"].clone())?)
    }}

{methods_block}
}}
"#,
            title        = info.title,
            version      = info.version,
            types_block  = types_block,
            methods_block = methods_block,
        )
    }

    // ── Schema → Rust type ────────────────────────────────────────────────────

    /// Convert a JSON Schema value to a Rust type name, registering any new
    /// named types that need to be emitted.
    fn schema_to_type(&mut self, schema: &Value, name_hint: &str) -> String {
        let Some(obj) = schema.as_object() else {
            return "Value".to_string();
        };
        if obj.is_empty() {
            return "Value".to_string();
        }

        // oneOf ────────────────────────────────────────────────────────────────
        if let Some(variants) = obj.get("oneOf").and_then(Value::as_array) {
            // Filter out empty-schema wildcards (ANY/ELISION from the C++ side).
            let meaningful: Vec<&Value> = variants
                .iter()
                .filter(|v| !v.as_object().map(|o| o.is_empty()).unwrap_or(false))
                .collect();

            return match meaningful.len() {
                0 => "Value".to_string(),
                1 => self.schema_to_type(meaningful[0], name_hint),
                _ => self.emit_one_of_enum(name_hint, &meaningful),
            };
        }

        match obj.get("type").and_then(Value::as_str) {
            Some("string")  => "String".to_string(),
            Some("boolean") => "bool".to_string(),
            Some("null")    => "()".to_string(),
            Some("number")  => {
                if obj.get("x-bitcoin-unit").and_then(Value::as_str) == Some("unix-time") {
                    "u64".to_string()
                } else {
                    "f64".to_string()
                }
            }
            Some("array")  => self.array_type(obj, name_hint),
            Some("object") => self.object_type(obj, name_hint),
            _              => "Value".to_string(),
        }
    }

    fn array_type(
        &mut self,
        obj: &serde_json::Map<String, Value>,
        name_hint: &str,
    ) -> String {
        // Fixed-length tuple (ARR_FIXED in the C++ type system).
        if let Some(prefix_items) = obj.get("prefixItems").and_then(Value::as_array) {
            let item_hint = format!("{name_hint}Item");
            let types: Vec<String> = prefix_items
                .iter()
                .map(|item| self.schema_to_type(item, &item_hint))
                .collect();
            return format!("({})", types.join(", "));
        }

        let item_hint = format!("{name_hint}Item");
        let item_type = obj
            .get("items")
            .map(|items| self.schema_to_type(items, &item_hint))
            .unwrap_or_else(|| "Value".to_string());
        format!("Vec<{item_type}>")
    }

    fn object_type(
        &mut self,
        obj: &serde_json::Map<String, Value>,
        name_hint: &str,
    ) -> String {
        // Named struct from an explicit `properties` map.
        if let Some(props) = obj.get("properties").and_then(Value::as_object) {
            let struct_name = name_hint.to_pascal_case();

            if self.types.contains_key(&struct_name) {
                return struct_name;
            }
            // Insert a placeholder first to break potential infinite recursion
            // in self-referential schemas before we recurse into field types.
            self.types.insert(struct_name.clone(), String::new());

            let required: std::collections::HashSet<&str> = obj
                .get("required")
                .and_then(Value::as_array)
                .map(|arr| arr.iter().filter_map(Value::as_str).collect())
                .unwrap_or_default();

            // `additionalProperties: true` means the object may carry fields
            // not listed in `properties` (C++ Type::ELISION was present).
            let open = obj
                .get("additionalProperties")
                .and_then(Value::as_bool)
                .unwrap_or(false);

            let mut field_lines: Vec<String> = Vec::new();
            for (key, prop_schema) in props {
                let field_hint = format!("{struct_name}{}", key.to_pascal_case());
                let rust_type  = self.schema_to_type(prop_schema, &field_hint);
                let is_req     = required.contains(key.as_str());
                let rust_type  = if is_req {
                    rust_type
                } else {
                    format!("Option<{rust_type}>")
                };

                let field_name   = safe_ident(&key.to_snake_case());
                let needs_rename = field_name.trim_start_matches("r#") != key.as_str();

                // Build the #[serde(...)] attribute combining rename + skip_serializing_if
                // into a single attribute to avoid stacked attribute noise.
                let mut serde_opts: Vec<String> = Vec::new();
                if needs_rename {
                    serde_opts.push(format!(r#"rename = "{}""#, key));
                }
                if !is_req {
                    serde_opts.push(r#"skip_serializing_if = "Option::is_none""#.to_string());
                }
                let serde_attr = if serde_opts.is_empty() {
                    String::new()
                } else {
                    format!("    #[serde({})]\n", serde_opts.join(", "))
                };

                // Field-level doc comment from the property's "description" key.
                let desc = prop_schema
                    .get("description")
                    .and_then(Value::as_str)
                    .unwrap_or("");
                let doc_attr = if desc.is_empty() {
                    String::new()
                } else {
                    let lines = desc
                        .lines()
                        .map(|l| format!("    /// {}", l.trim_end()))
                        .collect::<Vec<_>>()
                        .join("\n");
                    format!("{lines}\n")
                };

                field_lines.push(format!(
                    "{doc_attr}{serde_attr}    pub {field_name}: {rust_type},"
                ));
            }

            if open {
                field_lines.push(
                    "    #[serde(flatten)]\n    pub extra: HashMap<String, Value>,".to_string(),
                );
            }

            let def = format!(
                "#[derive(Debug, Clone, Deserialize, Serialize)]\npub struct {struct_name} {{\n{}\n}}\n",
                field_lines.join("\n")
            );
            self.types.insert(struct_name.clone(), def);
            return struct_name;
        }

        // Dynamic object (OBJ_DYN / OBJ_USER_KEYS) – additionalProperties holds
        // the value schema.
        if let Some(add_props) = obj.get("additionalProperties") {
            if add_props.as_bool() != Some(false) {
                let val_hint = format!("{name_hint}Value");
                let val_type =
                    if add_props.is_object() && !add_props.as_object().unwrap().is_empty() {
                        self.schema_to_type(add_props, &val_hint)
                    } else {
                        "Value".to_string()
                    };
                return format!("HashMap<String, {val_type}>");
            }
        }

        "HashMap<String, Value>".to_string()
    }

    fn emit_one_of_enum(&mut self, name_hint: &str, variants: &[&Value]) -> String {
        let enum_name = name_hint.to_pascal_case();
        if self.types.contains_key(&enum_name) {
            return enum_name;
        }
        self.types.insert(enum_name.clone(), String::new());

        let variant_lines: Vec<String> = variants
            .iter()
            .enumerate()
            .map(|(i, schema)| {
                let variant_hint = format!("{enum_name}V{i}");
                let rust_type    = self.schema_to_type(schema, &variant_hint);
                format!("    V{i}({rust_type}),")
            })
            .collect();

        let def = format!(
            "#[derive(Debug, Clone, Deserialize, Serialize)]\n#[serde(untagged)]\npub enum {enum_name} {{\n{}\n}}\n",
            variant_lines.join("\n")
        );
        self.types.insert(enum_name.clone(), def);
        enum_name
    }
}

// ─────────────────────────────────────────────────────────────────────────────

/// Format a multi-line description as indented `///` doc lines.
fn format_doc(text: &str, indent: usize) -> String {
    let pad     = " ".repeat(indent);
    let trimmed = text.trim_end_matches('\n');
    if trimmed.is_empty() {
        return String::new();
    }
    let lines: Vec<String> = trimmed
        .lines()
        .map(|l| format!("{pad}/// {}", l.trim_end()))
        .collect();
    format!("{}\n", lines.join("\n"))
}

const KEYWORDS: &[&str] = &[
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
    "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
    "mut", "pub", "ref", "return", "self", "static", "struct", "super", "trait", "true", "type",
    "union", "unsafe", "use", "where", "while",
];

/// Escape Rust reserved keywords by prefixing with `r#`.
fn safe_ident(name: &str) -> String {
    if name.is_empty() {
        return "_field".to_string();
    }
    if name.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        return format!("_{name}");
    }
    if KEYWORDS.contains(&name) {
        return format!("r#{name}");
    }
    name.to_string()
}
